apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-s3-connector-config
data:
  application-k8s.yml: |
    spring:
      application:
        name: kafka-s3-connector
      profiles:
        active: k8s,prod

    # Production Kafka Configuration
    kafka:
      bootstrap-servers: kafka-cluster:9092
      consumer:
        group-id: prod-kafka-s3-connect-cluster
        session-timeout-ms: 30000
        heartbeat-interval-ms: 10000
        max-poll-records: 2000
        max-poll-interval-ms: 600000

    # Production S3 Configuration
    s3:
      region: us-west-2
      bucket-name: production-data-lake
      path-style-access: false

    # High-performance connector configuration
    connector:
      topics:
        user-events:
          processing:
            batch-size: 5000
            flush-interval: 30
            max-retries: 5
        order-events:
          processing:
            batch-size: 5000
            flush-interval: 30
            max-retries: 5

    # Production server configuration
    server:
      tomcat:
        threads:
          max: 800
          min-spare: 50
        max-connections: 2000
        accept-count: 200

    # Production logging
    logging:
      level:
        root: INFO
        com.company.kafkaconnector: INFO
        org.apache.kafka: WARN
      file:
        name: /app/logs/kafka-s3-connector.log
      logback:
        rollingpolicy:
          max-file-size: 500MB
          max-history: 90
          total-size-cap: 20GB

    # Circuit breaker for production
    resilience4j:
      circuitbreaker:
        instances:
          s3-write:
            failure-rate-threshold: 25
            wait-duration-in-open-state: 120s
            sliding-window-size: 50
            minimum-number-of-calls: 20
      retry:
        instances:
          s3-write:
            max-attempts: 5
            wait-duration: 500ms
            exponential-backoff-multiplier: 2
            max-wait-duration: 30s