apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-s3-connector
spec:
  template:
    spec:
      containers:
      - name: kafka-s3-connector
        resources:
          requests:
            cpu: 750m
            memory: 1.5Gi
          limits:
            cpu: 3000m
            memory: 6Gi
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s,staging"